### ISSUE TITLE
can't save settings (in options.txt) +1

### ISSUE THREAD

**Issue by idkwidsb** [Dev0Louis/Unbound-FoV#2] opened 2023-11-04 06:10 UTC
everything is go back to the default settings everytime when i launch the game...
fix it，please————

:)

**Comment by Dev0Louis** [comment] 2023-11-04 12:14
Duplicate of https://github.com/Dev0Louis/Unbound-FoV/issues/1

**Closed as not planned by Dev0Louis** 2023-11-04 12:14 UTC
Labels: duplicate
